# Email and password authentication flow
# NOT recommended, neither me nor Discord
username = ""
password = ""

# Token authentication flow
# RECOMMENDED
# Uses the token stored in keyrings if empty, will attempt to
# store the token if the first token works
token = ""

[ properties ]
	# Refer to ./6cord -h for details.
	# Defaults are rather defined in the code, which is why this
	# should only be used as a reference on how to configure.
	# Keys are optional.
	show-channels = true
	chat-padding = 2
	sidebar-ratio = 3
	sidebar-indent = 2
	hide-blocked = true
	trigger-typing = true
	foreground-color = 15
	background-color = -1
	command-prefix = "[${GUILD}${CHANNEL}] "
	default-status = "Send a message or input a command"
	syntax-highlight-colorscheme = "emacs"
	show-emoji-urls = true
	obfuscate-words = false
	image-fetch-timeout = 1
	image-width = 400
	image-height = 400
	shorten-url = true

